train_config:
  raw_dataset_dir:
    - "/home/exx/datasets/data_pick_01"
    - "/home/exx/datasets/data_pick_01_04,05"
    - "/home/exx/datasets/data_pick_02"
    - "/home/exx/datasets/data_pick_03"
    - "/home/exx/datasets/data_pick_04"
    - "/home/exx/datasets/data_pick_05"
    - "/home/exx/datasets/data_pick_06"
    - "/home/exx/datasets/data_pick_07"
    - "/home/exx/datasets/data_pick_07_05"
    - "/home/exx/datasets/data_pick_08"
  output_dataset_dir: "/home/exx/datasets/pick_s_GCEV_a_relative_pose_gripper_t2_r6_random"
  ckpt_dir: "ckpt_dir/pick_s_GCEV_a_relative_pose_gripper_t2_r6_random"
  # reference_frame: [457.2, 0, 280, -180, 0, 90] # default
  # reference_frame: [457.2, 0, 280, 173, 10, 90]
  reference_frame: [457.2, -304.8, 280, 187, -10, 90]
  noisy_reference: True
  noisy_reference_type: "random" # vs "fixed"
  noise_level_translation: 2 # in cm
  noise_level_rotation: 6 # in degrees
  kl_weight : 10
  lr: 1e-05
  num_epochs: 8000
  batch_size: 32
  crop_image: False
  crop_ratio: 0.7
  mask_image: False
  mask_ratio: 0.5


task_config:
  task_name: "PIH_place"
  logging_yaml: "logging_05012025.yaml"
  episode_len: 990
  task_name: "PIH_gains_s_GCEV_a_relative_pose"
  state_category: ['GCEV']
  state_dim: 6
  action_category: ['relative_pose', 'gripper']
  action_dim: 7
  camera_names: ['realsense', 'arducam']
  num_queries: 60
  num_episodes: 40
  policy_class: "ACT"
  hidden_dim: 512
  dim_feedforward: 3200
  temporal_agg: True

eval_config:
  ckpt_dir: "act/ckpt_dir/pick_s_GCEV_a_relative_pose_gripper_t2_r6_random"  
  ckpt_name: "policy_last.ckpt"
  num_episodes: 1
  num_queries: 60
  episode_len: 2500
  frequency: 30
  temporal_agg: True