device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/indy_peg_hole/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_05_19_23-24-36_Pick_LowRes_indy_peg_hole_new/checkpoint/300.pt'  
      n_warmups: 10
    - configs_root_dir: 'configs/indy_peg_hole/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_05_19_23-59-47_Pick_HiRes_indy_peg_hole_new/checkpoint/300.pt'  
      n_warmups: 10
  pick_critic_kwargs:
    configs_root_dir: 'configs/indy_peg_hole/pick_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_05_20_00-35-23_Pick_EBM_indy_peg_hole_new/checkpoint/300.pt'
    n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/indy_peg_hole/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_05_20_01-12-36_Place_LowRes_indy_peg_hole_new/checkpoint/300.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/indy_peg_hole/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_05_20_02-23-58_Place_HiRes_indy_peg_hole_new/checkpoint/300.pt'
      n_warmups: 10
  place_critic_kwargs: 
    configs_root_dir: 'configs/indy_peg_hole/place_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_05_20_03-36-29_Place_EBM_indy_peg_hole_new/checkpoint/300.pt'
    n_warmups: 10
