train_config:
  raw_dataset_dir:
    - "/home/exx/datasets/data_pattern_platform_01"
    - "/home/exx/datasets/data_pattern_platform_02"
    - "/home/exx/datasets/data_pattern_platform_03"
    - "/home/exx/datasets/data_pattern_platform_04"
    - "/home/exx/datasets/data_pattern_platform_05"
    - "/home/exx/datasets/data_pattern_platform_06"
    - "/home/exx/datasets/data_pattern_platform_07"
    - "/home/exx/datasets/data_pattern_platform_08"
  output_dataset_dir: "/home/exx/datasets/s_GCEV_FT_a_relative_pose_gain_t1_r3_fixed_pattern_platform_try"
  ckpt_dir: "ckpt_dir/s_GCEV_FT_a_relative_pose_gain_t1_r3_fixed_pattern_platform_try"
  # reference_frame: [558.80, 0, 370, 180, 0, 90]
  # reference_frame: [558.80, 15, 365.07, -175, 10, 90]
  reference_frame: [457.49966180718434, -42.26409100420928, 307.1084579937928, 149.94775257458681, -19.89053906565085, 142.65171910599253]
  noisy_reference: True
  noisy_reference_type: "fixed" # "random" vs "fixed"
  noise_level_translation: 1 # in cm
  noise_level_rotation: 3 # in degrees
  kl_weight : 10
  lr: 1e-05
  num_epochs: 8000
  batch_size: 32
  crop_image: False
  crop_ratio: 0.7
  mask_image: False
  mask_ratio: 0.5

  fix_episode_length: False

task_config:
  task_name: "PIH_place"
  logging_yaml: "logging_05012025.yaml"
  episode_len: 822
  task_name: "PIH_gains_s_GCEV_a_relative_pose"
  state_category: ['GCEV', 'FT']
  state_dim: 12
  action_category: ['relative_pose', 'gains']
  action_dim: 12
  camera_names: ['realsense', 'arducam']
  num_queries: 60
  num_episodes: 85
  policy_class: "ACT"
  hidden_dim: 512
  dim_feedforward: 3200
  temporal_agg: True

  rot6d: False

eval_config:
  ckpt_dir: "/home/horowitzlab/ros2_ws_clean/src/inference_pipeline/inference_pipeline/act/ckpt_dir/s_GCEV_FT_a_relative_pose_gain_t1_r3_fixed_pattern_platform_try"  
  ckpt_name: "policy_best.ckpt"
  num_episodes: 1
  num_queries: 60
  episode_len: 2500
  frequency: 30
  temporal_agg: True