train_config:
  raw_dataset_dir:
    - "/home/exx/datasets/data_pattern_01"
    - "/home/exx/datasets/data_pattern_02"
    - "/home/exx/datasets/data_pattern_03"
    - "/home/exx/datasets/data_pattern_04"
    - "/home/exx/datasets/data_pattern_05"
    - "/home/exx/datasets/data_pattern_06"
    - "/home/exx/datasets/data_pattern_07"
    - "/home/exx/datasets/data_pattern_08"
  output_dataset_dir: "/home/exx/datasets/s_GCEV_FT_a_relative_pose_gain_t2_r6_fixed_pattern"
  ckpt_dir: "ckpt_dir/s_GCEV_FT_a_relative_pose_gain_t2_r6_fixed_pattern"
  reference_frame: [552.10, 0, 365.07, -155, 0, 90]
  # reference_frame: [538.80, -45.33, 334.25, -30, 180, 0] # default 30 deg
  noisy_reference: True
  noisy_reference_type: "fixed" # vs "fixed"
  noise_level_translation: 2 # in cm
  noise_level_rotation: 6 # in degrees
  kl_weight : 10
  lr: 1e-05
  num_epochs: 8000
  batch_size: 32
  crop_image: False
  crop_ratio: 0.7
  mask_image: False
  mask_ratio: 0.5


task_config:
  task_name: "PIH_place"
  logging_yaml: "logging_05012025.yaml"
  episode_len: 700
  task_name: "PIH_gains_s_GCEV_a_relative_pose"
  state_category: ['GCEV', 'FT']
  state_dim: 12
  action_category: ['relative_pose', 'gains']
  action_dim: 12
  camera_names: ['realsense', 'arducam']
  num_queries: 60
  num_episodes: 82
  policy_class: "ACT"
  hidden_dim: 512
  dim_feedforward: 3200
  temporal_agg: True

eval_config:
  ckpt_dir: "act/ckpt_dir/s_GCEV_FT_a_relative_pose_gain_t2_r6_fixed_pattern"  
  ckpt_name: "policy_best.ckpt"
  num_episodes: 1
  num_queries: 60
  episode_len: 2500
  frequency: 30
  temporal_agg: True