train_config:
  raw_dataset_dir:
    - "/home/exx/datasets/data_pattern_platform_01"
    - "/home/exx/datasets/data_pattern_platform_02"
    - "/home/exx/datasets/data_pattern_platform_03"
    - "/home/exx/datasets/data_pattern_platform_04"
    - "/home/exx/datasets/data_pattern_platform_05"
    - "/home/exx/datasets/data_pattern_platform_06"
    - "/home/exx/datasets/data_pattern_platform_07"
    - "/home/exx/datasets/data_pattern_platform_08"
  output_dataset_dir: "/home/exx/datasets/s_world_pose_FT_a_world_pose_gains_rot6d"
  ckpt_dir: "ckpt_dir/s_world_pose_FT_a_world_pose_gains_rot6d"
  reference_frame: [355.6, 0 , 370, -180, 0, 90]
  noisy_reference: False
  noisy_reference_type: "random" # "random" vs "fixed"
  noise_level_translation: 2 # in cm
  noise_level_rotation: 6 # in degrees
  kl_weight : 10
  lr: 1e-05 
  num_epochs: 12000
  batch_size: 32
  crop_image: False
  crop_ratio: 0.7
  mask_image: False
  mask_ratio: 0.5

  fix_episode_length: False

task_config:
  task_name: "PIH_place"
  logging_yaml: "logging_05012025.yaml"
  episode_len: 822
  state_category: ['world_pose','FT']
  state_dim: 15
  action_category: ['world_pose','gains']
  action_dim: 15
  camera_names: ['realsense', 'arducam']
  num_queries: 60
  num_episodes: 85
  policy_class: "ACT"
  hidden_dim: 512
  dim_feedforward: 3200
  temporal_agg: True
  rot6d: True

eval_config:
  ckpt_dir: "act/ckpt_dir/s_world_pose_FT_a_world_pose_gains_rot6d"  
  ckpt_name: "policy_best.ckpt"
  num_episodes: 1
  num_queries: 60
  episode_len: 600
  frequency: 30
  temporal_agg: True