device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/indy_peg_hole_double_pick/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole_double_pick/2025_05_22_21-11-45_Pick_LowRes_indy_peg_hole_double_pick/checkpoint/300.pt'  
      n_warmups: 10
    - configs_root_dir: 'configs/indy_peg_hole_double_pick/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole_double_pick/2025_05_22_21-45-32_Pick_HiRes_indy_peg_hole_double_pick/checkpoint/300.pt'  
      n_warmups: 10
  pick_critic_kwargs:
    configs_root_dir: 'configs/indy_peg_hole_double_pick/pick_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole_double_pick/2025_05_23_00-04-19_Pick_EBM_indy_peg_hole_double_pick/checkpoint/300.pt'
    n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/indy_peg_hole_double_pick/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole_double_pick/2025_05_23_11-22-15_Place_LowRes_indy_peg_hole_double_pick/checkpoint/300.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/indy_peg_hole_double_pick/place_highres'
      train_configs_file: 'train_configs.yaml'  
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole_double_pick/2025_05_23_11-56-32_Place_HiRes_indy_peg_hole_double_pick/checkpoint/300.pt'
      n_warmups: 10
  place_critic_kwargs: 
    configs_root_dir: 'configs/indy_peg_hole_double_pick/place_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: '/home/horowitzlab/ros2_ws_clean/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole_double_pick/2025_05_23_12-30-53_Place_EBM_indy_peg_hole_double_pick/checkpoint/300.pt'
    n_warmups: 10
