device: 'cuda'
model_kwargs:
  pick_models_kwargs:
    - configs_root_dir: 'configs/indy_peg_hole/pick_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_02_04_14-58-06_Pick_LowRes_indy_peg_hole_on_Shelf/checkpoint/250.pt' 
      n_warmups: 10
    - configs_root_dir: 'configs/indy_peg_hole/pick_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_02_04_15-17-51_Pick_HiRes_indy_peg_hole_on_Shelf/checkpoint/250.pt'  
      n_warmups: 10
  pick_critic_kwargs:
    configs_root_dir: 'configs/indy_peg_hole/pick_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: '/home/horowitzlab/ros2_ws/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_02_04_15-38-57_Pick_EBM_Indy_Peg_Hole/checkpoint/250.pt'
    n_warmups: 10
  place_models_kwargs:
    - configs_root_dir: 'configs/indy_peg_hole/place_lowres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_02_04_16-01-20_Place_LowRes_indy_peg_hole_on_Shelf/checkpoint/300.pt'
      n_warmups: 10
    - configs_root_dir: 'configs/indy_peg_hole/place_highres'
      train_configs_file: 'train_configs.yaml'
      task_configs_file: 'task_configs.yaml'
      checkpoint_dir: '/home/horowitzlab/ros2_ws/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_02_04_16-52-17_Place_HiRes_indy_peg_hole_on_Shelf/checkpoint/300.pt'
      n_warmups: 10
  place_critic_kwargs: 
    configs_root_dir: 'configs/indy_peg_hole/place_ebm'
    train_configs_file: 'train_configs.yaml'
    task_configs_file: 'task_configs.yaml'
    checkpoint_dir: '/home/horowitzlab/ros2_ws/src/pipeline/pipeline/diffusion_edf/checkpoints/indy_peg_hole/2025_02_04_17-42-41_Place_EBM_indy_peg_hole_on_Shelf/checkpoint/300.pt'
    n_warmups: 10
